# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Isabella Lu"
weight = 1

[zh-cn]
languageName = "中文"
languagedirection = "ltr"
title = "卢思成"
